# -*- coding: utf-8 -*-
"""Day 4 of Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uboPcpdHKzvYNk1es-U1tROkj4vQQvuX
"""

import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv("/content/covid_toy (1).csv")

df.sample(5)



from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

X_train

from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

transformer.fit_transform(X_train).shape

transformer.transform(X_test).shape















